Add non_automatic group type param to groups index
discourse/discourse pull request #10917
Opened 2020-10-14 07:21 UTC by angusmcleod

A list of all non automatic groups is sometimes needed when listing groups for an admin on a client consuming the API. I am specifically hoping to use this for improvments being made to https://github.com/discourse/wp-discourse/blob/master/lib/utilities.php#L217.

2020-10-14 13:39 UTC, pmusaraj requested changes
This looks nice, but it needs a translation, because the non_automatic filter shows up in the UI: 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/368961/95996811-15e4bb80-0e01-11eb-894b-b1b4cd6608b5.png">

2020-10-15 01:43 UTC, SamSaffron commented
I am not sure we need this in the UI ... too many choices

2020-10-15 09:49 UTC, angusmcleod commented
How about restricting it to API calls? i.e.

```
type_filters = type_filters - [:non_automatic] unless (is_api? || is_user_api?)
```

2020-10-19 04:31 UTC, angusmcleod commented
I've updated this to exclude the filter from the response, which precludes the missing string (and the UI clutter).

2020-10-20 22:45 UTC, SamSaffron approved these changes

2020-10-20 22:45 UTC, SamSaffron commented
Thanks @angusmcleod  looks good to me!

2020-10-20 22:46 UTC, merged