FEATURE: Ask user to confirm topic deletion when views exceed a certain amount
discourse/discourse pull request #11006
Opened 2020-10-23 00:21 UTC by lis2

Before deleting a topic that has a high number of views (default of 5000), the user will be prompted with a confirmation popup. This works for all delete buttons on the topic located in: `topic-timeline`, `topic-admin-menu`, `topic-footer-buttons`, and `post-menu` if the post's ID is 1.

The delete button will be disabled while deletion is in progress, to prevent any unwanted behavior.

A site setting is also available to change the minimum amount of views required to display the confirmation popup.

![image](https://user-images.githubusercontent.com/24194862/90439809-2b10c880-e0a4-11ea-814d-cfcef5f89aaf.png)

![discourse-delete-modal-confirm](https://user-images.githubusercontent.com/24194862/90439556-be95c980-e0a3-11ea-8eb5-eb419c5af52e.gif)

All kudos are going to @RickyC0626. I only rebased with master and added few qunit tests to ensure that this feature works as expected.

Original PR: https://github.com/discourse/discourse/pull/10459

2020-10-23 17:40 UTC, eviltrout requested changes

2020-10-23 17:40 UTC, eviltrout commented on app/assets/javascripts/discourse/tests/acceptance/topic-test.js
> +QUnit.test("Deleting a topic", async (assert) => {
This will need to be updated to our new acceptance test format

2020-10-27 01:44 UTC, SamSaffron commented
@lis2 happy to get this merged once tests are in the new format!

2020-10-28 17:03 UTC, eviltrout approved these changes

2020-10-29 01:55 UTC, SamSaffron commented
Lets get a slightly shorter name for the site setting @lis2 and then go ahead and merge

`min_topic_views_for_delete_confirm` 

Current name is a bit long.

2020-10-29 03:18 UTC, merged

2020-10-29 18:15 UTC, RickyC0626 commented
Thanks for the help!