FEATURE: Improve group settings and members management
discourse/discourse pull request #11878
Opened 2021-01-28 08:16 UTC by nbianca

This pull requests contains a series of improvements to groups settings and member management such as:

- Showing which users have set a group as primary
- Moving similar settings together under Effects
- Adding bulk select and actions to members page

2021-01-28 19:10 UTC, eviltrout approved these changes
Looks good! I added some comments.

2021-01-28 19:10 UTC, eviltrout commented on app/assets/javascripts/discourse/app/components/table-header-toggle-bulk.js
> +    const self = this;
You shouldn't need to use a `self` variable here. If you make `onClick = (sel, callback) => {` then its `this` will be the parent `this`.

2021-01-28 19:10 UTC, eviltrout commented on app/assets/javascripts/discourse/app/components/table-header-toggle-bulk.js
> +    onClick("button.bulk-select-all", function () {
Might as well make all these `() =>` functions too, since you aren't using `this`. (very minor)

2021-01-28 19:10 UTC, eviltrout commented on config/locales/client.en.yml
> +        make_owners_description: "Make selected users as owners of this group"
```suggestion
        make_owners_description: "Make selected users owners of this group"
```

2021-01-28 19:10 UTC, eviltrout commented on config/locales/client.en.yml
> +        make_primary_description: "Make this group primary for <b>%{username}</b>"
```suggestion
        make_primary_description: "Make this the primary group for <b>%{username}</b>"
```

2021-01-28 19:10 UTC, eviltrout commented on config/locales/client.en.yml
> +        remove_primary_description: "Remove this group as a primary of <b>%{username}</b>"
```suggestion
        remove_primary_description: "Remove this as the primary group for <b>%{username}</b>"
```

2021-01-28 19:10 UTC, eviltrout commented on config/locales/client.en.yml
> +        make_all_primary_description: "Make this group primary for all selected users"
```suggestion
        make_all_primary_description: "Make this the primary group for all selected users"
```

2021-01-28 19:11 UTC, pmusaraj requested changes
I pulled this locally, it looks great!

I noticed one minor issue, with bulk selection toggled on, hovering over the "Username" table header applies a hover effect to the header next to it.

2021-01-28 19:11 UTC, pmusaraj commented on app/assets/stylesheets/common/base/group.scss
> +    padding: 10px;
I don't think you need to specify padding for just this column, it already inherits padding from `td`.

2021-02-03 12:03 UTC, ZogStriP approved these changes

2021-02-03 13:10 UTC, pmusaraj approved these changes

2021-02-03 14:11 UTC, merged