DOCS: Updates docs for OSX dev with fontforge
discourse/discourse pull request #11956
Opened 2021-02-03 20:09 UTC by iamricard

`fondu` is no longer available via homebrew: _Error: fondu has been disabled because it is not maintained upstream!_ (since
Homebrew/homebrew-core#66396) and the `pkg` file available on `fondu`'s site doesn't seem to work on Big Sur. An alternative option is to use`fontforge`, which a little `python` script (it's definitely less short an harder to read, but it works). Additionally, it looks like the file *might* be called `ttc` instead.

I have also updated the URL for ImageMagick's `type_gen` because it now lives under `legacy.imagemagick.org` which causes `curl` to capture a 301 page instead.

2021-02-03 20:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/discourse/discourse?pullRequest=11956) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/discourse/discourse?pullRequest=11956) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/discourse/discourse?pullRequest=11956) it.</sub>

2021-02-04 15:41 UTC, CvX requested changes

2021-02-04 16:34 UTC, iamricard commented on docs/DEVELOPMENT-OSX-NATIVE.md
> +curl https://legacy.imagemagick.org/Usage/scripts/imagick_type_gen >
Oh whoops, you are right! Not sure what happened there. Thanks for catching that 😄

2021-02-04 22:27 UTC, CvX approved these changes
Looking good, thank you for the update! 😃

2021-02-04 22:28 UTC, merged