DEV: Fix warning about already initialized constants
discourse/discourse pull request #13202
Opened 2021-05-30 19:08 UTC by gschlager

2021-05-30 22:11 UTC, CvX approved these changes

2021-05-31 02:29 UTC, tgxworld requested changes
I know alot of places in our code base does this but I've always felt that this fix isn't right. Instead, we should try and figure out why the class is being loaded twice. 

This commit I made in the past might help: https://github.com/discourse/discourse/commit/069a109cbb8745ceb29035b2317c1b115052a7e0

2021-05-31 16:27 UTC, gschlager commented
@tgxworld I updated the PR. This fixes it for me as I've only seen the warnings in my dev environment. The piece of code I removed doesn't seem to be needed anymore.

2021-06-01 01:30 UTC, tgxworld approved these changes

2021-06-01 01:30 UTC, tgxworld commented
@gschlager Thank you! The fix looks good to me :+1:

2021-06-01 01:30 UTC, merged