FIX: "staff" and "admin" wasn't translatable in site settings
discourse/discourse pull request #13204
Opened 2021-05-30 21:14 UTC by gschlager

It also replaces the concatenated string with a translation.

2021-05-30 22:10 UTC, CvX approved these changes

2021-05-31 02:24 UTC, tgxworld commented on app/models/trust_level_and_staff_setting.rb
> +    if special_group?(value)
I think a test here will help prevent this from regressing in the future.

2021-05-31 02:25 UTC, tgxworld requested changes

2021-05-31 02:25 UTC, tgxworld commented on app/models/trust_level_and_staff_setting.rb
> +    if special_group?(value)
I think a test here will help prevent this from regressing in the future.

2021-06-01 09:13 UTC, gschlager commented
Superseded by https://github.com/discourse/discourse/pull/13224 which also adds the requested specs.

2021-06-01 09:13 UTC, closed without merging