FEATURE: adds uploads scope for API keys
discourse/discourse pull request #14941
Opened 2021-11-15 12:20 UTC by Firedrake

Context: https://meta.discourse.org/t/api-a-scope-with-access-to-uploads/208895

Testing this is not within my present familiarity with the discourse codebase.

2021-11-15 12:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/discourse/discourse?pullRequest=14941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/discourse/discourse?pullRequest=14941) before we can accept your contribution.<br/><hr/>**Roger Bell_West** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/discourse/discourse?pullRequest=14941) it.</sub>

2021-11-16 00:09 UTC, oblakeerickson requested changes
For testing for now you can add `uploads` to this line: https://github.com/discourse/discourse/blob/490fb51d2bb9397da72010e5afdb9fb9025f8ff7/spec/requests/admin/api_controller_spec.rb#L225

2021-11-16 00:09 UTC, oblakeerickson commented on config/locales/client.en.yml
> +              create: Upload a new image.
Change to "file" instead of "image" because discourse supports many different file types like .pdf or .mp4 and not just images.

2021-11-17 00:26 UTC, oblakeerickson commented
@Firedrake looks good, thanks! Can you go ahead and sign the CLA as well?

2021-11-17 00:38 UTC, Firedrake commented
I've signed the CLA. The email address I use here is not the same as the address I use on meta.discourse.

2021-11-17 16:31 UTC, oblakeerickson commented
@Firedrake ah thanks for signing the CLA. Are you okay adding that email as an additional email to github? so that it is tied to this commit? Otherwise I can't merge this in.

Looks like there are instructions for adding a secondary email [here](https://github.com/discourse/discourse/pull/14941#issuecomment-968857089):

> Roger Bell_West seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

2021-11-20 12:36 UTC, Firedrake commented
The email address should be set. Is this still blocked and do you need more action from my end?

2021-11-22 17:14 UTC, xfalcox commented
> The email address should be set. Is this still blocked and do you need more action from my end?

So is the commit email (`roger@firedrake.org`) set in https://github.com/settings/emails and verified?

2021-11-22 17:20 UTC, Firedrake commented
Ah, I see what they're doing. It is now.

2021-11-22 17:49 UTC, oblakeerickson approved these changes

2021-11-22 17:49 UTC, merged