FIX: don't validate and render the polls inside a quoted post.
discourse/discourse pull request #15019
Opened 2021-11-19 04:18 UTC by vinothkannans

Previously, we had issues while approving the posts since we validated the polls inside quotes.

2021-11-19 07:35 UTC, jjaffeux requested changes

2021-11-19 07:35 UTC, jjaffeux commented on plugins/poll/assets/javascripts/initializers/extend-for-poll.js
> +    const $polls = $(".poll", $elem).filter(function () {
please take every opportunity to remove jquery usage

2021-11-19 07:35 UTC, jjaffeux commented
There are also linting errors to fix.

2022-01-12 22:11 UTC, SamSaffron commented
This can wait till 2.9

@vinothkannans can you rebase.

2022-04-05 06:00 UTC, SamSaffron commented
@vinothkannans can you finish this one off? Looks like all that is left is to change to use https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName and we can merge this in.

2022-04-06 16:28 UTC, jjaffeux approved these changes

2022-04-15 11:03 UTC, merged