UX: organize topic admin menu into groups
discourse/discourse pull request #16489
Opened 2022-04-15 20:13 UTC by awesomerobot

Before:

<img width="299" alt="Screen Shot 2022-04-15 at 4 11 57 PM" src="https://user-images.githubusercontent.com/1681963/163627492-2aacd972-7fcb-4e8b-a843-62d7e198958f.png">

After:

<img width="264" alt="Screen Shot 2022-04-15 at 4 05 06 PM" src="https://user-images.githubusercontent.com/1681963/163627383-59b8c229-4081-49bf-9474-46eb3fc93c91.png">

2022-04-16 11:22 UTC, CvX requested changes

2022-04-16 11:22 UTC, CvX commented on app/assets/javascripts/discourse/app/widgets/topic-admin-menu.js
> +      new Map()
This fails if there are any buttons added by plugins that don't have `button_group` attribute

2022-04-16 11:24 UTC, CvX commented on app/assets/javascripts/discourse/app/widgets/topic-admin-menu.js
> +      new Map()
Scratch that. The issue is that `actionButtons` somehow can have `undefined` values:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/66961/163673133-a640ab20-3bb3-4bce-883a-2041ea75950e.png">

So the error is:

```
TypeError: Cannot read properties of undefined (reading 'button_group')
    at topic-admin-menu.js:341:1
```

2022-04-16 11:33 UTC, CvX commented
Two style notes:

1. Would probably be better if horizontal spacing around icons was even
2. A single pixel spacing between buttons would prevent them from being glued to each other when two are in active states

<img width="257" alt="Screen Shot 2022-04-16 at 13 30 05" src="https://user-images.githubusercontent.com/66961/163673323-a47a6f49-3732-4fab-bee6-3d8d621990f9.png">

2022-04-18 16:19 UTC, pmusaraj approved these changes

2022-04-25 20:02 UTC, merged