mbox importer improvements
discourse/discourse pull request #16557
Opened 2022-04-25 22:07 UTC by ldmosquera

Some small mbox importer improvements

2022-04-25 22:15 UTC, gschlager requested changes

2022-04-25 22:15 UTC, gschlager commented on script/import_scripts/mbox/support/indexer.rb
> +            if from_email =~ /lists.llvm.org/
the domain should be a setting as well

2022-04-27 20:45 UTC, ldmosquera commented on script/import_scripts/mbox/support/indexer.rb
> +            if from_email =~ /lists.llvm.org/
good catch - fixed + tested

2022-04-29 12:27 UTC, gschlager approved these changes

2022-04-29 16:24 UTC, merged