add yammer importer
discourse/discourse pull request #17651
Opened 2022-07-25 19:42 UTC by pfaffman

I wrote this import for yammer. It required a few additions to `generic_database`. I erred on the side of safety rather than  adding minimal code (i.e., it might have been better to add the uploads to the existing post code, but it seemed safer to just add standalone code to handle the uploads. Similarly, PMs are topics and posts, but I kept them separate.

2022-07-27 13:10 UTC, gschlager requested changes

2022-07-27 13:10 UTC, gschlager commented on script/import_scripts/yammer.rb
> +end
Why is there a `GenericDatabase` class in this file?

2022-07-27 13:10 UTC, gschlager commented on script/import_scripts/base/generic_database.rb
> +        )
I think the index and table aren't needed, otherwise it should reference the `pm_post` table.

2022-07-27 13:10 UTC, gschlager commented on script/import_scripts/base/generic_database.rb
> +      @db.execute 'CREATE UNIQUE INDEX IF NOT EXISTS topic_upload_unique ON topic_upload(topic_id, path)'
I think the index and table aren't needed, otherwise it should reference the `pm_topic` table.

2022-07-27 13:10 UTC, gschlager commented on script/import_scripts/yammer.rb
> +    @db.sort_posts_by_created_at
The sorting won't have any effect on PMs. Is that intentional?

2022-08-01 20:48 UTC, gschlager commented on script/import_scripts/base/generic_database.rb
> +    def fetch_sorted_pm_posts(last_row_id)
It's fine to modify the `GenerericDatabase` class.

> I'll see what I can do to clean this up in the next week or two.
>
> This is why I almost never manage to submit a PR for an import script. :shrug:

No worries.

2022-08-02 17:52 UTC, gschlager commented on script/import_scripts/base/generic_database.rb
> +    def fetch_sorted_pm_posts(last_row_id)
> modify the `generic_database.rb` file

2022-11-28 15:25 UTC, gschlager commented
@pfaffman Are you still planning to clean up this PR? Otherwise I'm going to close it.

2022-11-29 00:21 UTC, pfaffman commented
Sorry. I'll see what I can do by the end of the week.

2023-01-29 14:26 UTC, jjaffeux commented
@pfaffman do you think you will be able to get to this please?

2023-01-29 18:40 UTC, pfaffman commented
I think I addressed Gerhard's concerns. They were right, of course. I also found (at least?) one issue that he didn't notice. I have run it against the data that I have and it still appears to work. :-)

2023-01-29 18:53 UTC, jjaffeux commented
> This pull request has been mentioned on **Discourse Meta**. There might be relevant details there:
> 
> https://meta.discourse.org/t/can-i-import-users-and-conversations-from-yammer/42329/12

Good thanks, I see one conflict though, can you try to resolve it please?

2023-01-29 18:53 UTC, jjaffeux commented
@gschlager I leave it to you :p

2023-01-30 20:14 UTC, gschlager commented
Thanks @pfaffman. Seems to be good enough. I've fixed the remaining conflict and created https://github.com/discourse/discourse/pull/20074.

2023-01-30 20:14 UTC, closed without merging

2023-01-30 20:17 UTC, pfaffman commented
Thanks, @gschlager. Since I mostly work alone my git merge skills are weak indeed.