FIX: Support unicode in search advanced filter @
discourse/discourse pull request #18804
Opened 2022-10-31 08:56 UTC by dujiajun

Fix the bug mentioned in https://meta.discourse.org/t/no-search-result-if-filtered-by-unicode-username/243349

2022-10-31 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/discourse/discourse?pullRequest=18804) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/discourse/discourse?pullRequest=18804) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/discourse/discourse?pullRequest=18804) it.</sub>

2022-11-02 07:00 UTC, SamSaffron commented
Isn't .* going to catch spaces, eg: `@something something something`, I thought we already had a username regex, can we not use it? 

https://github.com/discourse/discourse/blob/7f01e67e1f0052aeed5bb56f0033428bfa2afeb8/app/models/site_setting.rb#L135-L135

2022-11-02 12:03 UTC, dujiajun commented
`SiteSetting.allowed_unicode_username_characters_regex` only include the non-ascii part. So I need to concatenate it with the ascii characters. In this way, I need to write the regex like "^\@([a-zA-Z0-9_\-.#{SiteSetting.unicode_usernames ?SiteSetting.allowed_unicode_username_characters :""}]+)$". However, this will break the unitest because `SiteSetting.unicode_usernames` is loaded before set in the test, and every change to allowed_unicode_username_characters need a restart to take effect. I have no idea about how to deal with this.

2022-11-14 04:04 UTC, dujiajun commented
@SamSaffron @gschlager, hello sam and gerhard, I change the regex to (\S+) and it seems to meet your requirements. I believe there is no need to use SiteSetting.allowed_unicode_username_characters_regex.

2022-11-15 10:13 UTC, gschlager requested changes

2022-11-15 10:13 UTC, gschlager commented on lib/search.rb
>      user_id = User.where(staged: false).where(username_lower: username).pluck_first(:id)
The username should be normalized in order to fully work with Unicode.

```suggestion
    username = User.normalize_username(match)

    user_id = User.not_staged.where(username_lower: username).pluck_first(:id)
```

2022-11-16 09:41 UTC, gschlager approved these changes
Looks good, thank you!

2022-11-16 09:42 UTC, merged