FEATURE: Allow `target` attribute in links in user_field descriptions
discourse/discourse pull request #19102
Opened 2022-11-18 06:15 UTC by mdoggydog

This change adds `target` to the set of attributes allowed by the HTML sanitizer which is applied to the description of a user_field.

The rationale for this change:

 * If one puts a link (`<a>...</a>`) in the description of a user_field that is present and/or required at sign-up, the expectation is that a prospective new user will click on that link during sign-up.
 * Without an appropriate `target` attribute on the link, the new page will be loaded in the same window/tab as the sign-up form, but this will obliterate any fields that the user had already filled-out on the form.  (E.g., hitting the back-button will return to an empty form.)
 * Such UX behavior is incredibly aggravating to new users.

This change allows an admin to add a `target` attribute to links, to instruct the browser to open them in a different window/tab, leaving a sign-up form intact.

2023-01-05 14:48 UTC, mdoggydog commented
@romanrizzi do you need anything more (e.g., from me) before this can get reviewed (and, hopefully, merged)?

2023-01-05 16:53 UTC, romanrizzi requested changes
I'm so sorry for not reviewing earlier, @mdoggydog. 

Thanks for taking the time to open the PR. We definitely want to allowlist this attribute. It'd be great if we could also make sure `rel='noopener'` gets added to the link. I'm thinking something like this:

```ruby
without_nofollow = false

self.description = Nokogiri::HTML5.fragment(self.description).tap do |doc|
  PrettyText.add_rel_attributes_to_user_content(doc, without_nofollow)
end.to_s
      
self.description = sanitize_field(self.description, additional_attributes: %w[target rel])
```

2023-01-05 22:25 UTC, mdoggydog commented
> Thanks for taking the time to open the PR. We definitely want to allowlist this attribute. It'd be great if we could also make sure `rel='noopener'` gets added to the link. I'm thinking something like this:
> 
> ```ruby
> without_nofollow = false
> 
> self.description = Nokogiri::HTML5.fragment(self.description).tap do |doc|
>   PrettyText.add_rel_attributes_to_user_content(doc, without_nofollow)
> end.to_s
>       
> self.description = sanitize_field(self.description, additional_attributes: %w[target rel])
> ```

I would not add the `add_rel_attibutes_to_user_content(...)` bit to this particular PR, because it is a different (albeit related) kind of change.  This PR is focused on allowing an admin to add more kinds of attributes to links.  (Also, properly testing this more complex addition will be more complex, etc, etc.)

Furthermore, I don't think that `add_rel_attributes_to_user_content()` is actually appropriate for this context.  It's really made for enforcing a safe policy on user-posted content (partially controlled by the `exclude rel nofollow domains` config param).  In this context here, we are dealing with links created by a site admin as part of the site configuration --- I think the site admin should be able to specify/not-specify a `rel` attribute as they see fit for whatever goal they are trying to accomplish.  Maybe the admin _does not_ want `noopener`?  Maybe the admin actually _does_ want a `nofollow`?  Who knows; let the admin figure it out.

That said, I am completely open to adding `rel` as an additional attribute to this PR, so that the admin can do whatever they need to.

2023-01-06 13:17 UTC, romanrizzi commented
Fair enough - I think we can be laxer here. Let's merge it in its current state and revisit if we need to allow more attributes.

2023-01-06 13:17 UTC, romanrizzi approved these changes

2023-01-06 13:18 UTC, merged