FEATURE: Implement SiteSetting to Allow Anonymous Likes
discourse/discourse pull request #22131
Opened 2023-06-15 15:42 UTC by meltingmettle

This pull request adds a SiteSetting to allow admins to enable or disable anonymous liking.  

Thank you guys for creating and maintaining Discourse.  This is my first contribution to Discourse so please let me know if I'm missing anything.

2023-06-15 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/discourse/discourse?pullRequest=22131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/discourse/discourse?pullRequest=22131) before we can accept your contribution.<br/><hr/>**Emmett Ling** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/discourse/discourse?pullRequest=22131) it.</sub>

2023-06-15 16:19 UTC, kevinchen234 commented on spec/lib/guardian_spec.rb
> +      before { SiteSetting.allow_anonymous_posting = true }
Hmm, I've never seen this convention before.  Wondering if you want to mock this instead?
```suggestion
      before do
        allow(SiteSetting).
          to receive(:allow_anonymous_posting).
          and_return(true)
      end
```

2023-06-22 18:17 UTC, pmusaraj submitted a review, later dismissed
Thanks @meltingmettle, the PR looks good. I am curious, what does the like popup look like in this scenario? I would expect it to be a list of anonymized user avatars. Is that correct? 

Approving, will look into merging it shortly.

2023-06-23 06:10 UTC, nattsw requested changes
I think there are some UX issues here:

We still need to comply to `post_undo_action_window_mins`, which isn't happening. Ideally after X mins, the anonymous user should see this.

<img width="311" alt="Screenshot 2023-06-23 at 2 08 21 PM" src="https://github.com/discourse/discourse/assets/1555215/9e42a6db-9624-4d1d-9333-757592948a57">

The current bug now is that when the anon user clicks on the red ❤️ to undo the like, the frontend shows that the "like" is removed, but when you refresh the page it is actually still liked.

2023-06-23 20:29 UTC, meltingmettle commented on config/site_settings.yml
> +  allow_anonymous_likes:
Thank you for the review!  I've addressed your comments in the latest commits. 😀

2023-06-23 20:31 UTC, meltingmettle commented on lib/guardian.rb
> +      )
stree really wanted this. :/ 

Originally this looked like:
`return SiteSetting.allow_anonymous_likes? && obj.class == PostAction && obj.is_like? && obj.user_id == @user.id if if anonymous?`

2023-07-07 02:07 UTC, meltingmettle commented
Friendly bump!  Thank you! @nattsw @pmusaraj

2023-07-12 16:45 UTC, nattsw commented
Hey there @meltingmettle, the issue hasn't been addressed. This is what I am seeing now with the newest commit.

https://github.com/discourse/discourse/assets/1555215/5fc3705c-5079-4c01-9251-87ef5c9d5c2a

This is what needs to be shown:

https://github.com/discourse/discourse/assets/1555215/b4e10c52-1a54-4909-b723-191ddf97e0ac

We need to abide by `post_undo_action_window_mins`. This **disallows** the user from unliking the post after the value in the site setting.

2023-07-17 17:06 UTC, nattsw commented
@meltingmettle 

I traced the attribute from the css class:

<img width="1240" alt="Screenshot 2023-07-17 at 10 45 09 PM" src="https://github.com/discourse/discourse/assets/1555215/1b855df0-05f2-46a5-872d-a635121c35f0">

https://github.com/discourse/discourse/blob/a982b6765f9e2da14213f36061fe3bafec00d701/app/assets/javascripts/discourse/app/widgets/post-menu.js#L166-L181

then 

https://github.com/discourse/discourse/blob/3bde7ae4338edaffac44b8fdce9f97cb0e6f5b3b/app/assets/javascripts/discourse/app/lib/transform-post.js#L260

then 

https://github.com/discourse/discourse/blob/3bde7ae4338edaffac44b8fdce9f97cb0e6f5b3b/app/assets/javascripts/discourse/app/models/action-summary.js#L7

then, I suspect the problem is with this line:

https://github.com/discourse/discourse/blob/e214fc38ed14143e702a9e3f2d2b7a2a0ffbc572/app/serializers/post_serializer.rb#L299-L308

In the case where the user is not anon, the "can_act" value is not present. Conversely, when the user is anon, "can_act" is present. There's probably an issue here with the scope.

Can you take a stab at figuring this one?

2023-07-18 22:46 UTC, meltingmettle commented
Thank you for the tip! That was super helpful! I’ve pushed a patch, manually verified the behavior, and added additional test coverage. 

It’s ready for another round of review when you have the chance. 😄

2023-07-21 12:46 UTC, nattsw approved these changes
Woohoo!

🚀 

Will merge this once tests are passing

EDIT: Merged `main` due to failing spec due to webdriver update.

2023-07-21 13:21 UTC, merged