DEV: Move Bookmark modal/component to use d-modal
discourse/discourse pull request #22532
Opened 2023-07-11 04:57 UTC by martin-brennan

c.f. https://meta.discourse.org/t/converting-modals-from-legacy-controllers-to-new-dmodal-component-api/268057

This also converts the Bookmark component to a Glimmer
component.

2023-07-12 06:48 UTC, martin-brennan commented
Plugin frontend failing test will be fixed when the DE PR is merged.

2023-07-12 06:53 UTC, martin-brennan commented on app/assets/javascripts/discourse/app/components/bookmark-list.js
> +        bookmark: new BookmarkFormData(bookmark),
This BookmarkFormData thing is not super ideal but I didn't want to go into the rabbit hole of changing Bookmark model to not use RestModel at the same time as well.

2023-07-12 08:18 UTC, davidtaylorhq approved these changes

2023-07-13 18:31 UTC, janzenisaac requested changes

2023-07-13 18:31 UTC, janzenisaac commented on app/assets/javascripts/discourse/app/components/modal/bookmark.hbs
> +        @class="bookmark-options-button"
```suggestion
        @action={{this.toggleShowOptions}}
        class="bookmark-options-button"
```

2023-07-13 18:31 UTC, janzenisaac commented on app/assets/javascripts/discourse/app/components/modal/bookmark.hbs
> +        @class="bookmark-options-button"
```suggestion
        @action={{this.toggleShowOptions}}
        class="bookmark-options-button"
```

2023-07-13 18:31 UTC, janzenisaac commented on app/assets/javascripts/discourse/app/components/modal/bookmark.hbs
> +        @id="save-bookmark"
```suggestion
        id="save-bookmark"
```

2023-07-13 18:31 UTC, janzenisaac commented on app/assets/javascripts/discourse/app/components/modal/bookmark.hbs
> +          @action={{action "delete"}}
```suggestion
          class="delete-bookmark btn-danger"
          @action={{this.delete}}
```

2023-07-14 05:38 UTC, martin-brennan commented on app/assets/javascripts/discourse/app/components/modal/bookmark.js
> +  }
Oh I didn't realise that `willDestroy` was left around for the lifecycle, thanks!

2023-07-14 05:59 UTC, martin-brennan commented
@janzenisaac I've fixed up all the review comments now, LMK if it's all good :) Thanks for the review!

2023-07-14 16:00 UTC, janzenisaac commented on app/assets/javascripts/discourse/app/components/modal/bookmark.js
> +  @tracked flashType = "error";
We can drop this here in favor of adding the string directly to the `<DModal>`

```
<DModal @flashType="error">
``` 

as it doesn't look like we are manipulating the value.

2023-07-14 16:00 UTC, janzenisaac approved these changes

2023-07-17 00:14 UTC, merged