DEV: Remove the upload processing placeholder
discourse/discourse pull request #23851
Opened 2023-10-09 17:24 UTC by CvX

Just a the single "Uploading…" placeholder. End user doesn't benefit much from knowing at what point in the processing pipeline their upload is. 😃

2023-10-10 01:12 UTC, martin-brennan requested changes
Hmm while I agree it's not really necessary to change the placeholder every time a different preprocessor is done, IMO we should still show Processing... until all of the preprocessors are done. Then we have parity with the status at the bottom of the composer that says "Processing Upload" too.

2023-10-10 01:12 UTC, martin-brennan commented on app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
> +    this.placeholders = new Map();
Nice, map works much better here 👍

2023-10-10 01:18 UTC, martin-brennan commented on app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
> -    this._onPreProcessProgress((file) => {
I think we could still leave this off, and just change this code:

https://github.com/discourse/discourse/blob/bb342bafe9a9d41f912c49e2eeda3edb66c60b11/app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js#L304-L309

To use the `processingPlaceholder` from the beginning...then when `_onPreProcessComplete` is fired replace it with the uploading placeholder

2023-10-10 01:19 UTC, martin-brennan commented on app/assets/javascripts/discourse/app/mixins/composer-upload-uppy.js
> -        placeholderData.uploadPlaceholder.replace("...", "…"),
I think this `replace()` could move to inside the `_uploadPlaceholder` function instead.

2023-10-10 13:03 UTC, CvX commented
> IMO we should still show Processing... until all of the preprocessors are done. Then we have parity with the status at the bottom of the composer that says "Processing Upload" too.

I'd change that composer status to display only "Uploading" too 😅 Does it make any difference to the user if it's processing vs uploading-uploading? Do other platforms differentiate between under-the-hood steps? 😃

2023-10-11 02:39 UTC, martin-brennan commented
@CvX Yes actually, Slack does for example:

![image](https://github.com/discourse/discourse/assets/920448/64193c22-15f8-4469-9cb8-db1ed8362000)
![2023-10-11_09-55](https://github.com/discourse/discourse/assets/920448/80a2e853-c025-42e1-ac24-0b17f97e6b16)

Discord as well:

![image](https://github.com/discourse/discourse/assets/920448/05021e0a-6d68-4658-930a-370c51974306)

Google Drive:

![image](https://github.com/discourse/discourse/assets/920448/878aebab-9595-4613-8543-5ca401a3b758)
![2023-10-11_12-38](https://github.com/discourse/discourse/assets/920448/dee5e851-ee9b-4f54-9c63-ab233a6b1e45)

So yes, we should keep the differentiation between the two phases; especially since at some point we may want to add post-processing to the pipeline. Happy to have an internal design/product topic about it too if you'd like.

2023-12-26 01:45 UTC, closed without merging